config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register' 
  },
  controllers: {
    registrations: :register,
    omniauth_callbacks: :omniauth_callbacks
  }
  
  root 'home#index'
  resources :login
  resources :register

  put 'user/choose_tool/:tool', to: 'home#choose_tool'
  post 'transactions/upload', to: 'upload_csv#upload'
  delete 'transactions/upload/:csv_id', to: 'upload_csv#destroy'

  resources :upload_csv
  resources :categorise
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :transactions
  has_many :prospective_transactions, foreign_key: 'prospective_category_id', class_name: 'Transaction'

  scope :other, -> { find_by(name: 'Other') }
end

app/models/csv_upload.rb
class CsvUpload < ApplicationRecord

  belongs_to :user
  has_many :transactions, dependent: :destroy
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :category, required: false
  belongs_to :prospective_category, required: false, class_name: 'Category'

  belongs_to :user, required: true

  scope :other, lambda {
    joins(:prospective_category)
      .where(prospective_category: { name: 'Other' })
  }
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :transactions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_google(email:, google_display_name:, google_id:, social_photo_url:)
    create_with(
      google_id: google_id,
      google_display_name: google_display_name,
      social_photo_url: social_photo_url
    ).find_or_create_by!(
      email: email,
    ) do |user|
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categorise_controller.rb
class CategoriseController < ApplicationController
  def index
    transactions_for_user = current_user.transactions.joins(:prospective_category)

    grouped_transactions = transactions_for_user.group_by do |transaction|
      transaction.prospective_category.name
    end

    @categories_with_spending = grouped_transactions.map do |category, transactions|
      { category: category.split(' ').join('_'), sum: transactions.map(&:amount).sum }
    end

    @categories_with_spending.sort_by! { |k| -k[:sum] }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  before_action :go_to_upload, only: :index

  def go_to_upload
    # we don't want to automatically redirect if the user hit the 'previous' btn.
    return if request&.referer&.include?("upload_csv")
    redirect_to upload_csv_index_path if current_user.selected_budget_workflow.present?
  end

  def choose_tool
    current_user.selected_budget_workflow = params[:tool]
    current_user.save

    render :json => { redirect_path: upload_csv_index_path }
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    user = User.from_google(from_google_params)
    if user.present?
      sign_out_all_scopes
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect user, event: :authentication
    else
      flash[:alert] = t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to new_user_session_path
    end
  end

  protected

  def after_omniauth_failure_path_for(_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end

  private

  def from_google_params
    @from_google_params ||= {
      google_id: auth.uid,
      email: auth.info.email,
      google_display_name: auth.info.name,
      social_photo_url: auth.info.image
    }
  end

  def auth
    @auth ||= request.env['omniauth.auth']
  end
end

app/controllers/register_controller.rb
class RegisterController < Devise::RegistrationsController
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(
        :first_name,
        :last_name,
        :email,
        :password,
      )
    end
  end
end

app/controllers/upload_csv_controller.rb
# frozen_string_literal: true

# Controller to take CSV uploads and create Transactions from them
class UploadCsvController < ApplicationController
  require 'csv'

  before_action :authenticate_user!

  def index
    @uploads = CsvUpload.where(
      user: current_user
    )
  end

  def upload
    csv = CsvUpload.create(
      bank: params['bank'],
      user_id: params['user_id'],
      filename: params[:file].original_filename,
      user: current_user
    )
    create_transaction_records(csv) # would be good to do this in worker so doesn't hold up rendering

    render json: csv
  end

  def destroy
    csv = CsvUpload.find(params[:csv_id])
    csv.destroy

    render json: csv
  end

  private

  def create_transaction_records(csv)
    transactions = []
    places_service = GooglePlacesService.new

    CSV.foreach(params['file'].tempfile, headers: true).each do |row|
      transaction = Transaction.new(
        amount: row['Amount'],
        date: row['Date'],
        particulars: row['Particulars'],
        reference: row['Reference'],
        details: row['Details'],
        code: row['Code'],
        transaction_type: row['Type'],
        user: current_user,
        csv_upload_id: csv.id
      )
      places_service.call(transaction)
      transaction.save
    end

    # just doing this for now as we're not categorising yet
    Transaction.transaction do
      transactions.map(&:save)
    end

    # group_transactions(transactions)
  end

  def upload_params
    params.permit(:bank, :file)
  end

  def group_transactions(transactions)
    # group transactions
    groups = transactions.group_by { |t| [t.details, t.particulars] }
    # loop over group
    groups.each do |_group_field_array, group_transaction_array|
      # find the category for first transaction in group
      suggested_category = group_transaction_array.first.categorise
      # apply the category to the group
      group_transaction_array.each do |transaction|
        transaction.prospective_category_id = Category.find_by(name: suggested_category.category).id
        transaction.save
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/views/categorise/index.html.erb
<% categories = json_escape(@categories_with_spending.to_json) %>
<left-navigation>
  <category-breakdown categories=<%= categories %>></category-breakdown>
</left-navigation>

app/views/home/index.html.erb
<select-budget-workflow 
  selected=<%= current_user.selected_budget_workflow.to_s %>
  token=<%= form_authenticity_token %>>
</select-budget-workflow>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gemino</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Overpass:300,400,600,700" rel="stylesheet">

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= javascript_pack_tag 'vue_pack', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'erb_pack', 'data-turbolinks-track': 'reload' %>
  </head>

  <% if notice.present? %>
    <p class="notice"><%= notice %></p>
  <%end %>

  <body class="bg-shade-1 antialiased">
    <div data-behavior="vue">
      <%= yield %>
    </div>
  </body>
</html>

app/views/login/index.html.erb
<div class="h-16 w-full flex flex-row items-center bg-white border-solid border-shade-3">
  <img alt='logo' class='w-12 flex mt-2 ml-4' src='images/logo-only.png'>
  <span class='flex ml-2 text-3xl'>Gemino</span>

  <div class='flex ml-auto mr-4'>
    <button class='btn-secondary text-primary-2 no-underline w-20 text-center'>
      About
    </button>

    <%= link_to 'Login', login_index_path, class: 'btn-secondary text-primary-2 no-underline w-20 text-center mr-6' %>

    <%= link_to 'Create an account', register_index_path, class: 'btn-secondary border border-solid border-primary-1 no-underline' %>
  </div>
</div>

<div class='flex items-center relative justify-center bg-red mt-4' style='height: calc(100vh - 64px)'>
  <div style='width: 578px' class='relative'>
    <div id='login_form' style="width: 464px; max-width: 100%" class='bg-white px-8 pt-8 pb-4 mt-8 rounded-sm mx-auto sm:w-full'>

      <h2 class='text-xl font-semibold text-center text-primary-2'>
        Log in
      </h2>
      
      <div class='flex justify-center mt-6'>
        <button class="flex hover:btn-google-hover hover:text-primary-3 transition text-primary-2 relative justify-center items-center leading-normal rounded border p-3 w-3/5">
          <img class='w-5' src='images/google-g.png'/>
          <span class='ml-3'>Log in with Google</span>
        </button>
      </div>

      <div class='flex mt-6'>
        <hr class='border-t flex-grow border-shade-3'>
        <p style="line-height: 0px;" class='ml-6 mr-6 text-sm text-primary-2'>or</p>
        <hr class='border-t flex-grow border-shade-3'>
      </div>

      <div class='mt-6'>
        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <%= f.label :email, class: "text-sm block text-primary-2 mt-4" do %>
            Email Address
          <% end %>
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "border rounded-sm h-12 mt-1 text-primary-2 focus:border-primary-1 p-4 w-full" %>

          <%= f.label :password, class: "text-sm block text-primary-2 mt-4" do %>
            Password
          <% end %>
          <%= f.password_field :password, autocomplete: "current-password", class: "border rounded-sm h-12 mt-1 text-primary-2 focus:border-primary-1 p-4 w-full" %>

          <div class='flex justify-center'>
            <%= f.submit "Log me in", class: "rounded bg-primary-1 p-3 text-white hover:btn-primary-hover transition leading-normal w-3/5 mt-8 z-10" %>
          </div>

          <div class='flex justify-center'>
            <button class='btn-secondary transition hover:btn-secondary-hover w-3/5 z-10 text-center no-underline appearance-none'>
              Forgot your password?
            </button>
          </div>
        <% end %>
      </div>
    </div>
    <div class='block sm:block hidden' style='height: 153px'></div>
    <img class='absolute sm:block bottom-0 hidden' src='/illustrations/img-reg-people.png' />
  </div>
</div>

app/views/register/index.html.erb
<div class="h-16 w-full flex flex-row items-center bg-white border-solid border-shade-3">
  <img alt='logo' class='w-12 flex mt-2 ml-4' src='images/logo-only.png'>
  <span class='flex ml-2 text-3xl'>Gemino</span>

  <div class='flex ml-auto mr-4'>
    <button class='btn-secondary text-primary-2 no-underline w-20 text-center'>
      About
    </button>

    <%= link_to 'Login', login_index_path, class: 'btn-secondary text-primary-2 no-underline w-20 text-center mr-6' %>

    <%= link_to 'Create an account', register_index_path, class: 'btn-secondary border border-solid border-primary-1 no-underline' %>
  </div>
</div>

<div class='flex items-center relative justify-center bg-red' style='height: calc(100vh - 64px)'>
  <div style='width: 578px' class='relative'>
    <div id='login_form' style="width: 464px; max-width: 100%" class='bg-white px-8 pt-8 pb-4 mt-8 rounded-sm mx-auto sm:w-full'>

      <h2 class='text-xl font-semibold text-center text-primary-2'>
        Create an account
      </h2>
      
      <div class='flex justify-center mt-6'>
        <button class="flex hover:btn-google-hover hover:text-primary-3 transition text-primary-2 relative justify-center items-center leading-normal rounded border p-3 w-3/5">
          <img class='w-5' src='images/google-g.png'/>
          <span class='ml-3'>Sign up with Google</span>
        </button>
      </div>

      <div class='flex mt-6'>
        <hr class='border-t flex-grow border-shade-3'>
        <p style="line-height: 0px;" class='ml-6 mr-6 text-sm text-primary-2'>or create an account</p>
        <hr class='border-t flex-grow border-shade-3'>
      </div>

      <div class='mt-6'>
        <form>
          <div class="flex justify-between">
            <div class="flex-col">
              <label class="text-sm block text-primary-2 mt-4">
                First name
              </label>
              <input class="border rounded-sm h-12 mt-1 text-primary-2 focus:border-primary-1 p-4 w-full" />
            </div>
            
            <div class="flex-col ml-4">
              <label class="text-sm block text-primary-2 mt-4">
                Last name
              </label>
              <input class="border rounded-sm h-12 mt-1 text-primary-2 focus:border-primary-1 p-4 w-full" />
            </div>
          </div>

          <label class="text-sm block text-primary-2 mt-4">
            Email address
          </label>
          <input class="border rounded-sm h-12 mt-1 text-primary-2 focus:border-primary-1 p-4 w-full" />
          
          <label class="text-sm block text-primary-2 mt-4">
            Create a password
          </label>
          <input class="border rounded-sm h-12 mt-1 text-primary-2 focus:border-primary-1 p-4 w-full" />

          <div class='flex justify-center'>
            <button class="rounded bg-primary-1 p-3 text-white hover:btn-primary-hover transition leading-normal w-3/5 mt-8 z-10">
              Sign up
            </button>
          </div>

          <div class='flex justify-center'>
            <%= link_to('Already have an account?', login_index_path, class: "btn-secondary transition hover:btn-secondary-hover w-3/5 z-10 text-center no-underline appearance-none") %>
          </div>
        </form>
      </div>
    </div>
    <div class='block sm:block hidden' style='height: 153px'></div>
    <img class='absolute sm:block bottom-0 hidden' src='/illustrations/img-reg-people.png' />
  </div>
</div>

app/views/upload_csv/index.html.erb
<left-navigation>
  <upload-csv
    token=<%= form_authenticity_token %>
    uploads="<%= @uploads.to_json %>"
  >
  </upload-csv>
</left-navigation>